
/* Drop Tables */

DROP TABLE SYSTEM.MEMBER0130 CASCADE CONSTRAINTS;


/* Create Tables */

CREATE TABLE SYSTEM.MEMBER0130
(
	USERID varchar2(100 char) NOT NULL,
	USERPW varchar2(100 char) NOT NULL,
	AGE number(3,0) NOT NULL,
	NAME varchar2(100 char) NOT NULL,
	CONSTRAINT SYS_C007111 PRIMARY KEY (USERID)
);



